ROTM/ROTM/Models/ContactViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ROTM.Models
{
    public class ContactViewModels
    {   
        [Required]
        [EmailAddress]
        public string From { get; set; }
        [Required]
        public string Subject { get; set; }
        [Required]
        public string Body { get; set; }
    }
}

ROTM/ROTM/Controllers/HomeController.cs
using ROTM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace ROTM.Controllers
{

    public class HomeController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        [AllowAnonymous]
        public ActionResult Contact()
        {
            ViewBag.Message = "If you have any problems with the managment system please feel free to get into contact with us via this contact page.";
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Contact(ContactViewModels contactViewModel)
        {
            ViewBag.Message = "If you have any problems with the managment system please feel free to get into contact with us via this contact page.";

            if (ModelState.IsValid)
            {
                try
                {
                    MailMessage msz = new MailMessage();
                    msz.From = new MailAddress(contactViewModel.From);//Email which you are getting 
                                                         //from contact us page 
                    msz.To.Add("info@repsonthemove.com");//Where mail will be sent 
                    msz.Subject = contactViewModel.Subject;
                    msz.Body = contactViewModel.Body;
                    SmtpClient smtp = new SmtpClient();

                    smtp.Host = "nl1-wss2.a2hosting.com";

                    smtp.Port = 25;

                    smtp.Credentials = new System.Net.NetworkCredential
                    ("info@repsonthemove.com", "3o3fE@k4");

                    smtp.EnableSsl = true;

                    smtp.Send(msz);

                   // ModelState.Clear();
                    //info@repsonthemove.com upg$H101
                    //This is for an emal service Remeber this !
                    ViewBag.StatusMessage = $"Your Message has been sent successfully ";
                    return View(contactViewModel);
                }
                catch (Exception ex)
                {

                   // ModelState.Clear();
                    ViewBag.StatusMessage = $"Sorry we are facing a problem here" + ex;
                }
            }
            return View(contactViewModel);
        }
    }
}

ROTM/ROTM/Controllers/bookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ROTM;

namespace ROTM.Controllers
{
    [Authorize]
    public class bookingsController : Controller
    {
        private Entities db = new Entities();

        // GET: bookings
        public ActionResult Index()
        {
<<<<<<< HEAD
            var bookings = db.bookings.Include(b => b.address).Include(b => b.booking_type).Include(b => b.client).Include(b => b.employee);
=======

            ViewData["CurrentFilter"] = searchString;

            var bookings = from s in (db.bookings.Include(b => b.address).Include(b => b.booking_type).Include(b => b.client).Include(b => b.employee)) select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                bookings = bookings.Where(s => s.Booking_Name.Contains(searchString) || s.Booking_Date.ToString().Contains(searchString) || s.Booking_Start_Time.ToString().Contains(searchString) || s.Booking_End_Time.ToString().Contains(searchString));
            }

            //var bookings = db.bookings.Include(b => b.address).Include(b => b.booking_type).Include(b => b.client).Include(b => b.employee);
>>>>>>> parent of 0eed6af... Validation and TrainingCourseInstanceWorking
            return View(bookings.ToList());
        }

        // GET: bookings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            booking booking = db.bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // GET: bookings/Create
        public ActionResult Create()
        {
            ViewBag.Address_ID = new SelectList(db.addresses, "Address_ID", "Street_Name");
            ViewBag.Booking_Type_ID = new SelectList(db.booking_type, "Booking_Type_ID", "Booking_Type_Name");
            ViewBag.Client_ID = new SelectList(db.clients, "Client_ID", "Client_Name");
            ViewBag.Employee_ID = new SelectList(db.employees, "Employee_ID", "Employee_Name");
            return View();
        }

        // POST: bookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Booking_ID,Booking_Name,Booking_Date,Booking_Start_Time,Booking_End_Time,Booking_Type_ID,Client_ID,Employee_ID,Address_ID")] booking booking)
        {
            if (ModelState.IsValid)
            {
                db.bookings.Add(booking);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Address_ID = new SelectList(db.addresses, "Address_ID", "Street_Name", booking.Address_ID);
            ViewBag.Booking_Type_ID = new SelectList(db.booking_type, "Booking_Type_ID", "Booking_Type_Name", booking.Booking_Type_ID);
            ViewBag.Client_ID = new SelectList(db.clients, "Client_ID", "Client_Name", booking.Client_ID);
            ViewBag.Employee_ID = new SelectList(db.employees, "Employee_ID", "Employee_Name", booking.Employee_ID);
            return View(booking);
        }

        // GET: bookings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            booking booking = db.bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            ViewBag.Address_ID = new SelectList(db.addresses, "Address_ID", "Street_Name", booking.Address_ID);
            ViewBag.Booking_Type_ID = new SelectList(db.booking_type, "Booking_Type_ID", "Booking_Type_Name", booking.Booking_Type_ID);
            ViewBag.Client_ID = new SelectList(db.clients, "Client_ID", "Client_Name", booking.Client_ID);
            ViewBag.Employee_ID = new SelectList(db.employees, "Employee_ID", "Employee_Name", booking.Employee_ID);
            return View(booking);
        }

        // POST: bookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Booking_ID,Booking_Name,Booking_Date,Booking_Start_Time,Booking_End_Time,Booking_Type_ID,Client_ID,Employee_ID,Address_ID")] booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(booking).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Address_ID = new SelectList(db.addresses, "Address_ID", "Street_Name", booking.Address_ID);
            ViewBag.Booking_Type_ID = new SelectList(db.booking_type, "Booking_Type_ID", "Booking_Type_Name", booking.Booking_Type_ID);
            ViewBag.Client_ID = new SelectList(db.clients, "Client_ID", "Client_Name", booking.Client_ID);
            ViewBag.Employee_ID = new SelectList(db.employees, "Employee_ID", "Employee_Name", booking.Employee_ID);
            return View(booking);
        }

        // GET: bookings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            booking booking = db.bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // POST: bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            booking booking = db.bookings.Find(id);
            db.bookings.Remove(booking);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ROTM/ROTM/Controllers/registration_tokenController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using ROTM;

namespace ROTM.Controllers
{
    public class registration_tokenController : Controller
    {
        private Entities db = new Entities();

        // GET: registration_token
        public ActionResult Index()
        {
            var registration_token = db.registration_token.Include(r => r.access_level).Include(r => r.employee);
            return View(registration_token.ToList());
        }

        //// GET: registration_token/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    registration_token registration_token = db.registration_token.Find(id);
        //    if (registration_token == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(registration_token);
        //}

        // GET: registration_token/Create
        public ActionResult Create()
        {
            ViewBag.Access_Level_ID = new SelectList(db.access_level, "Access_Level_ID", "Access_Level_Name");
            ViewBag.Employee_ID = new SelectList(db.employees, "Employee_ID", "Employee_Name");
            return View();
        }

        // POST: registration_token/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Registration_Token_ID,Registration_Token1,New_Email,Access_Level_ID,Employee_ID")] registration_token registration_token)
        {
            RNGCryptoServiceProvider rngCryptoServiceProvider = new RNGCryptoServiceProvider();
            byte[] randomBytes = new byte[6];
            rngCryptoServiceProvider.GetBytes(randomBytes);

            if (ModelState.IsValid)
            {
                registration_token.Registration_Token1 = Convert.ToBase64String(randomBytes);
                registration_token.Employee_ID = null;
                db.registration_token.Add(registration_token);
                db.SaveChanges();

                //info@repsonthemove.com upg$H101
                //This is for an emal service Remeber this !
                MailMessage mail = new MailMessage("no-reply@repsonthemove.com", registration_token.New_Email);
                SmtpClient client = new SmtpClient();
                client.Port = 25;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                client.Credentials = new System.Net.NetworkCredential("no-reply@repsonthemove.com", "k1Yvi2&5");
                client.Host = "nl1-wss2.a2hosting.com";
                mail.Subject = "Registration Token";
                mail.Body = "Hi " + registration_token.New_Email + "\n\nHere is you registration token: " + Convert.ToBase64String(randomBytes) + "\nIf you are a manager you can ignore this token as it is just for security, go onto https://repsonthemove.com/Account/Register and register as a normal. " + "\n\nRegards" + "\nReps On The Move Team";
                client.Send(mail);



                return RedirectToAction("Index");
            }

            ViewBag.Access_Level_ID = new SelectList(db.access_level, "Access_Level_ID", "Access_Level_Name", registration_token.Access_Level_ID);
            ViewBag.Employee_ID = new SelectList(db.employees, "Employee_ID", "Employee_Name", registration_token.Employee_ID);
            return View(registration_token);
        }

        // GET: registration_token/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            registration_token registration_token = db.registration_token.Find(id);
            if (registration_token == null)
            {
                return HttpNotFound();
            }
            ViewBag.Access_Level_ID = new SelectList(db.access_level, "Access_Level_ID", "Access_Level_Name", registration_token.Access_Level_ID);
            ViewBag.Employee_ID = new SelectList(db.employees, "Employee_ID", "Employee_Name", registration_token.Employee_ID);
            return View(registration_token);
        }

        // POST: registration_token/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Registration_Token_ID,Registration_Token1,New_Email,Access_Level_ID,Employee_ID")] registration_token registration_token)
        {
            if (ModelState.IsValid)
            {
                db.Entry(registration_token).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Access_Level_ID = new SelectList(db.access_level, "Access_Level_ID", "Access_Level_Name", registration_token.Access_Level_ID);
            ViewBag.Employee_ID = new SelectList(db.employees, "Employee_ID", "Employee_Name", registration_token.Employee_ID);
            return View(registration_token);
        }

        // GET: registration_token/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            registration_token registration_token = db.registration_token.Find(id);
            if (registration_token == null)
            {
                return HttpNotFound();
            }
            return View(registration_token);
        }

        // POST: registration_token/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            registration_token registration_token = db.registration_token.Find(id);
            db.registration_token.Remove(registration_token);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ROTM/ROTM/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ROTM/ROTM/Views/Home/Contact.cshtml
@model ROTM.Models.ContactViewModels

@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<p class="text-success">@ViewBag.StatusMessage</p>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.From, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.From, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.From, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div>
            <button type="submit"
                    class="btn btn-success">
                Send
            </button>
        </div>
    </div>

}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


@*<address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>*@

ROTM/ROTM/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div><hr /></div>
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">


    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">

            <div class="carousel-caption" role="option">
                <hr />
                <p style="color:black;">
                    Reps on the Move Managers Home Page
                </p>

            </div>
            <img src="~/Content/Images/ROTM.png" alt="ROTM logo" class="img-responsive center-block" height="200" width="250" />
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


<div class="row">
    <div class="col-md-3">
        <h2>Employee Management</h2>
        <ul>
            <li>@Html.ActionLink("Employee Index", "Index", "Employees")</li>
            <li>@Html.ActionLink("Employee Type", "Index", "Employee_type")</li>
            <li>@Html.ActionLink("Generate Registration Token", "Create", "registration_token")</li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Client Management</h2>
        <ul>
            <li>@Html.ActionLink("Client Index", "Index", "Clients")</li>
            <li>@Html.ActionLink("Client Type", "Index", "Client_type")</li>
            @*<li>@Html.ActionLink("Client Rating Type", "Index", "Employee_type")<a asp-area="" asp-controller="Client_Rating" asp-action="">Client Rating</a></li>*@
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Access Level</h2>
        <ul>
            <li>@Html.ActionLink("Access Level Index", "Index", "Access_Level")</li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Notifications</h2>
        <ul>
            <li><a asp-area="" asp-controller="" asp-action="">General marketing notification</a></li>
            <li><a asp-area="" asp-controller="" asp-action="">General internal notification</a></li>
        </ul>
    </div>

</div>
<div class="row">
    <div class="col-md-3">
        <h2>Reporting</h2>
        <ul>
            <li><a asp-area="" asp-controller="Employees" asp-action="">Employees Index</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Employee Milestone Management</h2>
        <ul>
            <li>@Html.ActionLink("Milestones", "Index", "Milestones")</li>
            <li>@Html.ActionLink("Setup Tasks", "Index", "Tasks")</li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Booking & Venue Management</h2>
        <ul>
            <li>@Html.ActionLink("Venues", "Index", "Venues")</li>
            <li>@Html.ActionLink("Address", "Index", "Addresses")</li>
            <li>@Html.ActionLink("Bookings", "Index", "bookings")</li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Training Course Management</h2>
        <ul>
            <li>@Html.ActionLink("Training Course", "Index", "Training_Course")</li>
            <li>@Html.ActionLink("Training Course Instance", "Index", "Training_Course_Instance")</li>
            <li>@Html.ActionLink("Training Course Type", "Index", "Training_Course_type")</li>
            <li>@Html.ActionLink("Instructor", "Index", "Instructors")</li>
            <li>@Html.ActionLink("Instructor Type", "Index", "Instructor_type")</li>
        </ul>
    </div>
</div>    